// GENERATED by tool/characters/bake.mjs — do not edit by hand.

part of 'characters.dart';

/// Every baked sticker: its pixel size and where the art sits inside the white
/// die-cut ring, as fractions of the sticker. Layout uses the art box, so a
/// character stands on a line by its feet, never by its ring.
const Map<String, StickerArt> _stickers = {
  'cat-sit-up': StickerArt(501, 685, 0.0247, 0.0181, 0.9753, 0.9819),
  'cat-wave': StickerArt(584, 685, 0.0211, 0.018, 0.9789, 0.982),
  'cat-wow': StickerArt(521, 685, 0.0236, 0.018, 0.9764, 0.982),
  'cat-lie': StickerArt(684, 390, 0.0175, 0.0307, 0.9825, 0.9693),
  'cat-sleep': StickerArt(685, 607, 0.018, 0.0204, 0.982, 0.9796),
  'cat-peek': StickerArt(685, 576, 0.0181, 0.0215, 0.9819, 1),
  'cat-peek-side': StickerArt(435, 685, 0.0287, 0.0182, 1, 0.9818),
  'cat-present': StickerArt(457, 684, 0.0261, 0.0174, 0.9739, 0.9826),
  'cat-point': StickerArt(532, 684, 0.0226, 0.0176, 0.9774, 0.9824),
  'cat-celebrate': StickerArt(447, 684, 0.0266, 0.0174, 0.9734, 0.9826),
  'cat-run': StickerArt(684, 437, 0.0175, 0.0273, 0.9825, 0.9727),
  'cat-sign': StickerArt(398, 684, 0.0299, 0.0174, 0.9701, 0.9826),
  'dog-sit-up': StickerArt(570, 685, 0.0217, 0.0181, 0.9783, 0.9819),
  'dog-wave': StickerArt(575, 685, 0.0216, 0.0181, 0.9784, 0.9819),
  'dog-wow': StickerArt(572, 685, 0.0216, 0.0181, 0.9784, 0.9819),
  'dog-lie': StickerArt(684, 386, 0.0176, 0.0312, 0.9824, 0.9688),
  'dog-sleep': StickerArt(685, 603, 0.0182, 0.0207, 0.9818, 0.9793),
  'dog-peek': StickerArt(684, 460, 0.0177, 0.0264, 0.9823, 1),
  'dog-peek-side': StickerArt(569, 686, 0.0225, 0.0186, 1, 0.9814),
  'dog-present': StickerArt(488, 684, 0.0246, 0.0175, 0.9754, 0.9825),
  'dog-point': StickerArt(507, 684, 0.0237, 0.0176, 0.9763, 0.9824),
  'dog-celebrate': StickerArt(426, 684, 0.0279, 0.0174, 0.9721, 0.9826),
  'dog-run': StickerArt(684, 461, 0.0175, 0.0259, 0.9825, 0.9741),
  'dog-sign': StickerArt(443, 684, 0.0269, 0.0174, 0.9731, 0.9826),
  'budgie': StickerArt(685, 647, 0.0182, 0.0193, 0.9818, 0.9807),
  'fish': StickerArt(684, 450, 0.0175, 0.0265, 0.9825, 0.9735),
  'hamster': StickerArt(547, 685, 0.0226, 0.0181, 0.9774, 0.9819),
  'rabbit': StickerArt(393, 684, 0.0303, 0.0174, 0.9697, 0.9826),
  'turtle': StickerArt(684, 549, 0.0178, 0.0221, 0.9822, 0.9779),
  'confetti-burst': StickerArt(641, 663, 0.0021, 0.002, 0.9979, 0.998),
  'heart-glossy': StickerArt(685, 608, 0.0184, 0.0207, 0.9816, 0.9793),
  'hearts-cluster': StickerArt(607, 663, 0.0025, 0.0023, 0.9975, 0.9977),
  'sparkle-burst': StickerArt(606, 664, 0.0029, 0.0027, 0.9971, 0.9973),
};
