// Bakes the in-app character stickers: trimmed to the art, white die-cut ring, no ring on a peek's cut edge.
//
//   node tool/characters/bake.mjs            (from zooboxi_app/, needs cwebp + the sapconnect node_modules)
//
// Sources are the one-time generated library in sapconnect/storage/app/public/creatives/bases/{chars,pop}.
// Writes assets/characters/*.webp and regenerates lib/core/characters/sticker_table.g.dart.
import { Resvg } from '/Users/mohamedmahgoub/Desktop/Muntajat/Muntajat_auto/sapconnect/node_modules/@resvg/resvg-js/index.js';
import { stats } from '/Users/mohamedmahgoub/Desktop/Muntajat/Muntajat_auto/sapconnect/resources/js/zooboxi-engine/png.mjs';
import fs from 'fs'; import { execFileSync } from 'child_process';
const BASE = '/Users/mohamedmahgoub/Desktop/Muntajat/Muntajat_auto/sapconnect/storage/app/public/creatives/bases';
const OUT = new URL('../../assets/characters', import.meta.url).pathname;
const TABLE = new URL('../../lib/core/characters/sticker_table.g.dart', import.meta.url).pathname;
const poses = ['sit-up','wave','wow','lie','sleep','peek','peek-side','present','point','celebrate','run','sign'];
const list = [];
for (const s of ['cat','dog']) for (const p of poses) list.push([`${s}-${p}`, 'chars']);
for (const n of ['budgie','fish','hamster','rabbit','turtle']) list.push([n, 'chars']);
for (const n of ['confetti-burst','heart-glossy','hearts-cluster','sparkle-burst']) list.push([n, 'pop']);
// which side is a straight cut (the sticker hides behind something there): no ring on that side
const CUT = { 'cat-peek-side': 'right', 'dog-peek-side': 'right', 'cat-peek': 'bottom', 'dog-peek': 'bottom' };
const RING = { 'confetti-burst': 0, 'sparkle-burst': 0, 'hearts-cluster': 0 };
const meta = {};
for (const [name, dir] of list) {
  const file = `${BASE}/${dir}/${name}.png`;
  const st = stats(file);
  let [x0, y0, x1, y1] = st.bbox; const bw = x1 - x0 + 1, bh = y1 - y0 + 1;
  const target = 660;                         // px on the long side of the art (≈220pt @3x)
  const k = Math.min(1, target / Math.max(bw, bh));
  const r = RING[name] ?? 11 / k;             // ring ≈ 11 output px, in source units
  const cut = CUT[name];
  const pad = { l: r + 2, t: r + 2, r: r + 2, b: r + 2 };
  if (cut === 'right') pad.r = 0; if (cut === 'bottom') pad.b = 0;
  const vx = x0 - pad.l, vy = y0 - pad.t, vw = bw + pad.l + pad.r, vh = bh + pad.t + pad.b;
  const b64 = fs.readFileSync(file).toString('base64');
  const ring = r > 0 ? `<filter id="d" x="-10%" y="-10%" width="120%" height="120%" color-interpolation-filters="sRGB">
      <feComponentTransfer in="SourceAlpha" result="h"><feFuncA type="linear" slope="6" intercept="-0.6"/></feComponentTransfer>
      <feMorphology in="h" operator="dilate" radius="${r.toFixed(1)}" result="m"/>
      <feGaussianBlur in="m" stdDeviation="${(r * 0.12).toFixed(1)}" result="mb"/>
      <feComponentTransfer in="mb" result="mm"><feFuncA type="linear" slope="3" intercept="-1"/></feComponentTransfer>
      <feFlood flood-color="#FFFFFF"/><feComposite in2="mm" operator="in" result="w"/>
      <feMerge><feMergeNode in="w"/><feMergeNode in="SourceGraphic"/></feMerge></filter>` : '';
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${vw}" height="${vh}" viewBox="${vx} ${vy} ${vw} ${vh}"><defs>${ring}</defs>
    <image href="data:image/png;base64,${b64}" x="0" y="0" width="${st.w}" height="${st.h}" ${r > 0 ? 'filter="url(#d)"' : ''}/></svg>`;
  const png = new Resvg(svg, { fitTo: { mode: 'width', value: Math.round(vw * k) } }).render().asPng();
  const tmp = `/tmp/zb_${name}.png`; fs.writeFileSync(tmp, png);
  const out = `${OUT}/${name}.webp`;
  execFileSync('cwebp', ['-quiet', '-q', '82', '-alpha_q', '92', '-m', '6', '-exact', tmp, '-o', out]);
  // art box inside the sticker, as fractions — lets the app stand a sticker on a line by its feet, not its ring
  meta[name] = { w: Math.round(vw * k), h: Math.round(vh * k), art: [pad.l / vw, pad.t / vh, (pad.l + bw) / vw, (pad.t + bh) / vh].map(v => +v.toFixed(4)) };
  process.stdout.write(`${name} ${meta[name].w}x${meta[name].h} ${Math.round(fs.statSync(out).size / 1024)}KB\n`);
}
const rows = Object.entries(meta).map(([k, v]) => `  '${k}': StickerArt(${v.w}, ${v.h}, ${v.art.join(', ')}),`).join('\n');
fs.writeFileSync(TABLE, `// GENERATED by tool/characters/bake.mjs — do not edit by hand.

part of 'characters.dart';

/// Every baked sticker: its pixel size and where the art sits inside the white
/// die-cut ring, as fractions of the sticker. Layout uses the art box, so a
/// character stands on a line by its feet, never by its ring.
const Map<String, StickerArt> _stickers = {
${rows}
};
`);
