#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan tinker --execute=\"echo json_encode(\\App\\Models\\SapInvoice::orderBy('id', 'desc')->take(5)->get()->toArray());\""
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
