#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan tinker --execute=\"echo json_encode(\\App\\Models\\SapInvoiceLine::whereIn('sap_invoice_id', \\App\\Models\\SapInvoice::where('card_code', 'C0000001')->pluck('id'))->count());\""
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
