#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan tinker --execute='DB::statement(\"SET FOREIGN_KEY_CHECKS=0;\"); \\App\\Models\\SapInvoiceLine::truncate(); \\App\\Models\\SapInvoice::truncate(); \\App\\Models\\WarehouseItemStock::truncate(); \\App\\Models\\SuggestedStockTransfer::truncate(); DB::statement(\"SET FOREIGN_KEY_CHECKS=1;\");'"
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
