#!/usr/bin/expect -f
match_max 100000
set timeout 10
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan queue:clear && php artisan tinker --execute=\"echo 'JOBS: ' . \\\Illuminate\\\\Support\\\\Facades\\\\DB::table('jobs')->count() . \\\"\\n\\\";\""
expect {
    "password:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
