#!/usr/bin/expect -f

set timeout 30
set ip "sapapi.muntajat.sa"
set user "sapapimuntajat"
set password "h23N1KXMIL#\$94"

spawn scp -o StrictHostKeyChecking=no app/Models/User.php $user@$ip:/home/sapapimuntajat/sapconnect_app/app/Models/
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "*$*"
send "cd sapconnect_app\r"
expect "*$*"

send "php artisan optimize:clear\r"
expect "*$*"

send "php artisan tinker update_user.php\r"
expect "*$*"

send "rm update_user.php\r"
expect "*$*"

send "exit\r"
expect eof
