#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && nohup php artisan tinker --execute='\\App\\Jobs\\FetchSapInvoicesJob::dispatchSync(app(\\App\\Services\\SAP\\SapClient::class));' > fetch.log 2>&1 &"
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
