#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn scp -o StrictHostKeyChecking=no -o PubkeyAuthentication=no verify_sap_fields.php sapapimuntajat@sapapi.muntajat.sa:sapconnect_app/verify_sap_fields.php
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no sapapimuntajat@sapapi.muntajat.sa "cd sapconnect_app && php verify_sap_fields.php"
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
