#!/usr/bin/expect -f
match_max 100000
set timeout -1
set password "h23N1KXMIL#\$94"
set user_host "sapapimuntajat@62.138.14.178"

spawn ssh -o StrictHostKeyChecking=no $user_host "cd sapconnect_app && php artisan tinker --execute=\"dump(\\App\\Models\\Warehouse::whereNotNull('sales_employee_code')->select('warehouse_code', 'sales_employee_code')->first());\""
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "" }
}
