#!/usr/bin/expect -f
match_max 100000
set password "h23N1KXMIL#\$94"
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan tinker --execute=\"echo 'NOW COUNT: ' . App\\\\Models\\\\StockTransfer::count() . \\\"\\n\\\";\""
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
