#!/usr/bin/expect -f
match_max 100000
set password "h23N1KXMIL#\$94"
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php artisan tinker --execute=\"echo 'JSON=' . json_encode(App\\\\Models\\\\StockTransfer::where('doc_num', '2600819')->get()->toArray()) . \\\"\\n\\\";\""
expect {
    "assword:" {
        send "$password\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
