#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn scp -o StrictHostKeyChecking=no routes/api.php app/Http/Controllers/Api/StoreController.php sapapimuntajat@62.138.14.178:sapconnect_app/
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && mv api.php routes/ && mv StoreController.php app/Http/Controllers/Api/ && php artisan cache:clear"
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
