#!/usr/bin/expect -f
match_max 100000
set timeout -1
set password "h23N1KXMIL#\$94"
set user_host "sapapimuntajat@62.138.14.178"
set app_dir "sapconnect_app"

spawn scp -o StrictHostKeyChecking=no app/Filament/RetailWidgets/StoreLevel/StoreSmartReplenishmentTable.php $user_host:$app_dir/app/Filament/RetailWidgets/StoreLevel/StoreSmartReplenishmentTable.php
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "Table uploaded successfully." }
}
