#!/usr/bin/expect -f
match_max 100000
set timeout -1
set password "h23N1KXMIL#\$94"
set user_host "sapapimuntajat@62.138.14.178"

spawn scp -o StrictHostKeyChecking=no app/Models/PurchaseOrder.php $user_host:sapconnect_app/app/Models/PurchaseOrder.php
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "uploaded model" }
}

spawn scp -o StrictHostKeyChecking=no app/Filament/Resources/SapPurchaseOrderResource.php $user_host:sapconnect_app/app/Filament/Resources/SapPurchaseOrderResource.php
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "uploaded resource" }
}
