#!/usr/bin/expect -f
match_max 100000
set timeout -1
spawn scp -o StrictHostKeyChecking=no app/Jobs/CalculateStockOpportunitiesJob.php sapapimuntajat@62.138.14.178:sapconnect_app/app/Jobs/CalculateStockOpportunitiesJob.php
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}

spawn scp -o StrictHostKeyChecking=no run_engine.php sapapimuntajat@62.138.14.178:sapconnect_app/run_engine.php
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}

spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php run_engine.php"
expect {
    "assword:" {
        send "h23N1KXMIL#\$94\r"
        exp_continue
    }
    eof {
        puts $expect_out(buffer)
    }
}
