#!/usr/bin/expect -f
match_max 100000
set timeout -1
set password "h23N1KXMIL#\$94"
set user_host "sapapimuntajat@62.138.14.178"
set app_dir "sapconnect_app"
set local_dir "."

spawn scp -o StrictHostKeyChecking=no $local_dir/app/Filament/Resources/SuggestedStockTransferResource.php $user_host:$app_dir/app/Filament/Resources/SuggestedStockTransferResource.php
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "Uploaded." }
}

spawn ssh -o StrictHostKeyChecking=no $user_host "cd sapconnect_app && php artisan view:clear && php artisan cache:clear && php artisan route:clear"
expect {
    "assword:" { send "$password\r"; exp_continue }
    eof { puts "Caches cleared." }
}
