#!/usr/bin/expect -f

set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"
send "php artisan tinker --execute=\"use Spatie\\Permission\\Models\\Role; Role::firstOrCreate(\\\['name' => 'Branch Manager'\\\]); echo \\\"Branch Manager Role Created!\\\\n\\\";\"\r"
expect "$*"
send "exit\r"
expect eof
