#!/usr/bin/expect -f

set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"

# Check Table Existence
send "php artisan tinker\r"
expect ">>>"
send "Schema::hasTable('sap_stock_transfers_prod');\r"
expect ">>>"
send "Schema::hasTable('sap_stock_transfers_test');\r"
expect ">>>"
send "exit\r"

send "exit\r"
expect eof
