#!/usr/bin/expect -f

set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"

# Run Migrations
send "php artisan migrate --force\r"

# Retry Test Command
send "php artisan sap:sync-stock-transfers --code=sync_stock_transfers_PPTC_V5_PROD\r"

send "exit\r"
expect eof
