#!/usr/bin/expect -f

set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn scp -o StrictHostKeyChecking=no oms_rename.tar.gz $user@$ip:/home/sapapimuntajat/oms_rename.tar.gz
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "tar -xzf oms_rename.tar.gz -C sapconnect_app\r"
send "rm oms_rename.tar.gz\r"
send "cd sapconnect_app\r"
send "php artisan optimize:clear\r"
send "exit\r"
expect eof
