#!/usr/bin/expect -f
set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn rsync -avz --exclude=.env --exclude=vendor --exclude=storage --exclude=.git -e "ssh -o StrictHostKeyChecking=no" /Users/mohamedmahgoub/Desktop/Muntajat/Muntajat_auto/sapconnect/ $user@$ip:/home/sapapimuntajat/sapconnect_app/
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip "cd sapconnect_app && php artisan migrate --force"
expect "*assword:*"
send "$password\r"
expect eof
