#!/usr/bin/expect

set timeout 20
spawn scp -o StrictHostKeyChecking=no debug_automations.php sapapimuntajat@62.138.14.178:/home/sapapimuntajat/sapconnect_app/debug_automations.php
expect "Password:"
send "Muntajat@2025\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php debug_automations.php"
expect "Password:"
send "Muntajat@2025\r"
expect eof
