#!/usr/bin/expect -f

set timeout 30
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"

# Generate Token via Tinker
send "php artisan tinker\r"
expect ">>>"

# Check if user exists, if not create, then token
send "\$user = App\\Models\\User::first();\r"
expect ">>>"
send "echo \$user->createToken('DocsToken')->plainTextToken;\r"
expect ">>>"

send "exit\r"
expect "$*"
send "exit\r"
expect eof
