#!/usr/bin/expect

set timeout 60

spawn scp -o StrictHostKeyChecking=no check_automation_status.php sapapimuntajat@62.138.14.178:/home/sapapimuntajat/sapconnect_app/check_automation_status.php
expect "Password:"
send "Muntajat@2025\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no sapapimuntajat@62.138.14.178 "cd sapconnect_app && php check_automation_status.php"
expect "Password:"
send "Muntajat@2025\r"
expect eof
