#!/usr/bin/expect -f

set timeout 60
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

# Upload Verification Script
spawn scp -o StrictHostKeyChecking=no verify_rbac_remote.php $user@$ip:/home/sapapimuntajat/sapconnect_app/verify_rbac_remote.php
expect "*assword:*"
send "$password\r"
expect eof

# Run it
spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"
send "php verify_rbac_remote.php\r"
send "rm verify_rbac_remote.php\r"
send "exit\r"
expect eof
