#!/usr/bin/expect -f

set timeout 300
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

# 1. Upload Debug Script
spawn scp -o StrictHostKeyChecking=no debug_stock_transfer_view.php $user@$ip:/home/sapapimuntajat/sapconnect_app/
expect "*assword:*"
send "$password\r"
expect eof

# 2. Run Debug Script
spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "*$*"
send "cd sapconnect_app\r"
send "php debug_stock_transfer_view.php\r"

expect "*$*"
send "exit\r"
expect eof
