#!/usr/bin/expect -f

set timeout 60
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn scp -o StrictHostKeyChecking=no seed_import_payload.php $user@$ip:/home/sapapimuntajat/sapconnect_app/seed_import_payload.php
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"
send "cat seed_import_payload.php | php artisan tinker\r"
expect "Seeding Complete"

send "rm seed_import_payload.php\r"
expect "$*"
send "exit\r"
expect eof
