#!/usr/bin/expect -f

set timeout 30
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"

send "ls -la config/\r"
expect "$*"

send "php artisan tinker --execute=\"dump(config('database.connections.mysql.options'));\"\r"
expect "$*"

send "exit\r"
expect eof
