#!/usr/bin/expect -f

set timeout 120
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn scp -o StrictHostKeyChecking=no sapconnect.tar.gz $user@$ip:/home/sapapimuntajat/
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "tar -xzf sapconnect.tar.gz -C sapconnect_app --strip-components=1\r"

expect "$*"
# Clear caches to ensure new classes are found
send "cd sapconnect_app\r"
send "php artisan optimize:clear\r"

expect "$*"
send "exit\r"
expect eof
