#!/usr/bin/expect -f

set timeout 60
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn scp -o StrictHostKeyChecking=no app/Http/Controllers/Controller.php $user@$ip:/home/sapapimuntajat/sapconnect_app/app/Http/Controllers/Controller.php
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"
send "php artisan route:list\r"

expect "$*"
send "exit\r"
expect eof
