#!/usr/bin/expect -f

set timeout 60
set ip "62.138.14.178"
set user "sapapimuntajat"
set password $env(DEPLOY_PASSWORD)

spawn scp -o StrictHostKeyChecking=no debug_view_record.php $user@$ip:/home/sapapimuntajat/sapconnect_app/debug_view_record.php
expect "*assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no $user@$ip
expect "*assword:*"
send "$password\r"

expect "$*"
send "cd sapconnect_app\r"
send "php artisan tinker debug_view_record.php\r"
send "exit\r"
expect eof
