import 'package:flutter/material.dart';
import 'package:exhibition_manager_app/core/storage/secure_storage.dart';

/// App Translations & Locale Controller
class AppLocalizations {
  AppLocalizations._();

  static const String _localeStorageKey = 'app_selected_locale';

  /// Live notifier for language changes across the entire app
  static final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('ar'));

  /// Current active language code
  static String get currentLanguage => localeNotifier.value.languageCode;

  /// Check if the current locale is Arabic
  static bool get isArabic => currentLanguage == 'ar';

  /// Translations map
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_title': 'Muntajat HUB',
      'app_subtitle': 'منصّة الفروع والمعارض',

      // Auth
      'login': 'تسجيل الدخول',
      'login_subtitle': 'أدخل بيانات الدخول للمتابعة',
      'email': 'البريد الإلكتروني',
      'email_hint': 'example@muntajat.sa',
      'password': 'كلمة المرور',
      'password_required': 'يرجى إدخال كلمة المرور',
      'email_required': 'يرجى إدخال البريد الإلكتروني',
      'email_invalid': 'بريد إلكتروني غير صالح',
      'unexpected_error': 'حدث خطأ غير متوقع',

      // Public landing (pre-login)
      'landing_welcome': 'مرحباً بك في',
      'company_news': 'أخبار الشركة',
      'about_company': 'عن الشركة',
      'news_empty': 'لا توجد أخبار حالياً',
      'loading_error': 'تعذّر تحميل المحتوى، حاول مرة أخرى',
      'read_more': 'اقرأ المزيد',
      'our_brands': 'علاماتنا التجارية',
      'our_branches': 'فروعنا',
      'directions': 'الاتجاهات',
      'branch_call': 'اتصال',
      'brand_products': 'منتجات البراند',
      'brand_no_products': 'لا توجد صور منتجات حالياً',
      'brand_founded': 'التأسيس',
      'brand_origin': 'المنشأ',
      'landing_news': 'آخر الأخبار',
      'stat_brands': 'علامة تجارية',
      'stat_branches': 'فرعاً ومعرضاً',
      'stat_cities': 'مدن',
      'brand_products_unit': 'منتج',
      'landing_footer_tag': 'الموزّع الرائد لأبرز العلامات في المملكة',
      'news_tag': 'خبر',
      'brand_featured': 'الأبرز',
      'tap_to_view': 'اضغط للعرض',
      'all_label': 'الكل',

      // OTP / phone login
      'login_with_email': 'البريد وكلمة المرور',
      'login_with_phone': 'برقم الجوال',
      'mobile_number': 'رقم الجوال',
      'mobile_number_hint': '05XXXXXXXX',
      'mobile_required': 'يرجى إدخال رقم الجوال',
      'otp_login_hint': 'سنرسل لك رمز تحقّق عبر رسالة نصية (SMS)',
      'send_otp': 'إرسال رمز التحقق',
      'otp_sent_to': 'تم إرسال رمز التحقق إلى',
      'enter_otp': 'أدخل رمز التحقق',
      'verify': 'تحقّق ودخول',
      'resend_otp': 'إعادة إرسال الرمز',
      'resend_in': 'إعادة الإرسال خلال {s} ثانية',
      'otp_invalid': 'رمز التحقق غير صحيح أو منتهي',
      'mobile_not_registered': 'رقم الجوال غير مسجّل، تواصل مع الإدارة',
      'change_number': 'تغيير الرقم',
      
      // Bottom Nav
      'nav_home': 'الرئيسية',
      'nav_showroom_pulse': 'النبض',
      'showroom_pulse_title': 'نبض المعرض',
      'nav_transfers': 'التحويلات',
      'nav_counting': 'الجرد',
      'nav_achievements': 'إنجازاتي',
      'nav_profile': 'حسابي',

      // Achievements / Gamification
      'achievements_subtitle': 'نقاطك وأوسمتك وترتيبك',
      'achievements_soon_title': 'إنجازاتك قادمة قريباً',
      'achievements_soon_subtitle': 'أكمل مهام الجرد لتجمع النقاط والأوسمة',

      // Cycle Counting (guided)
      'cycle_count': 'جرد دوري',
      'full_count': 'جرد سنوي',
      'status_filter_title': 'تصفية حسب الحالة',
      'items_to_count': 'الأصناف المطلوب جردها',
      'counted': 'تم العدّ',
      'pending_count': 'بانتظار',
      'remaining_items': 'متبقّي',
      'scan_to_count': 'مسح باركود',
      'complete_count': 'إكمال الجرد',
      'scan_at_least_one': 'امسح صنفاً واحداً على الأقل للإكمال',
      'count_completed': 'تم إكمال الجرد بنجاح 🎉',
      'cycle_auto_generated': 'تُنشأ مهام الجرد الدوري تلقائياً كل أسبوع',
      'no_targets': 'لا توجد أصناف مستهدفة في هذه المهمة',
      'class_label': 'الفئة',
      'overdue_label': 'متأخر',
      'due_label': 'مستحق',

      // Cycle detail — tabs & records
      'cycle_targets_tab': 'المطلوب جرده',
      'cycle_records_tab': 'سجلاتي',
      'counted_records': 'السجلات المُدخلة',
      'no_records_yet': 'لم تُسجّل أي عملية عدّ بعد',
      'no_records_yet_hint': 'امسح الأصناف لتسجيل عمليات العدّ',
      'entry_n': 'تسجيل {n}',
      'counted_products_n': 'المنتجات المجرودة ({n})',
      'edit_quantity': 'تعديل الكمية',
      'delete_record': 'حذف السجل',
      'delete_record_confirm': 'هل تريد حذف هذا السجل من الجرد؟',
      'update': 'تحديث',
      'delete': 'حذف',
      // Off-list scanner gating (cycle)
      'off_list_title': 'صنف خارج قائمة الجرد',
      'product_off_cycle_list': 'هذا المنتج خارج قائمة الجرد الدوري',
      'off_list_cannot_count': 'لا يمكن عدّ صنف خارج القائمة',
      'off_list_scans_n': '{n} مسح خارج القائمة',
      'counted_label': 'مجرود',

      // Quality Control
      'quality_tasks': 'مهام الجودة',
      'quality_section_subtitle': 'مهام مستحقة اليوم',
      'no_quality_tasks': 'لا توجد مهام جودة 🎉',
      'view_all': 'عرض الكل',
      'status_pending': 'قيد التنفيذ',
      'status_submitted': 'مكتملة',
      'proof_acknowledge': 'تأكيد',
      'proof_photo': 'صور',
      'proof_checklist': 'قائمة',
      'mark_done': 'تم الإنجاز',
      'submit_task': 'إرسال',
      'task_submitted': 'تم إكمال المهمة 🎉',
      'add_photo': 'إضافة صورة',
      'take_photo': 'التقاط صورة',
      'choose_from_gallery': 'من المعرض',
      'photos_progress': '{x} / {min} صور',
      'comment_optional': 'تعليق (اختياري)',
      'comment_required_label': 'تعليق (مطلوب)',
      'complete_all_items': 'أكمل جميع البنود للإرسال',
      'photo_required_badge': 'صورة مطلوبة',
      'acknowledge_hint': 'اضغط للتأكيد عند إنجاز المهمة',
      'overdue_badge': 'متأخرة',

      // Zooboxi Express Orders
      'zooboxi_urgent_orders': 'طلبات zooboxi العاجلة',
      'zooboxi_section_subtitle': 'طلبات سريعة بانتظار التجهيز',
      'no_urgent_orders': 'لا توجد طلبات عاجلة 🎉',
      'orders_new': 'جديدة',
      'orders_waiting': 'تنتظر',
      'orders_done': 'تمّت',
      'no_done_orders': 'لا توجد طلبات مجهّزة بعد',
      'status_done': 'تمّت',
      'nav_zooboxi': 'العاجلة',
      'status_preparing': 'قيد التجهيز',
      'order_no': 'طلب',
      'order_items': 'الأصناف',
      'express_delivery': 'توصيل سريع',
      'qty_short': 'الكمية',
      'currency': '\u{E900}',
      'minutes_ago': 'منذ {x} د',
      'hours_ago': 'منذ {x} س',
      'start_preparing': 'بدء التجهيز',
      'mark_prepared': 'تم التجهيز',
      'order_prepared_done': 'تم تجهيز الطلب ✓',
      'order_prepared_no_sync': 'تم التجهيز ✓ — تعذّر تحديث المتجر، ستتم المزامنة لاحقاً',

      // Gamification detail
      'points': 'نقطة',
      'level': 'المستوى',
      'streak': 'سلسلة',
      'weeks': 'أسبوع',
      'accuracy': 'الدقة',
      'this_month': 'هذا الشهر',
      'weekly_goal': 'الهدف الأسبوعي',
      'leaderboard': 'لوحة الترتيب',
      'rank_branch': 'ترتيب فرعك',
      'rank_in_branch': 'ترتيبك في الفرع',
      'rank_company': 'ترتيبك العام',
      'badges_title': 'الأوسمة',
      'branches': 'الفروع',
      'employees': 'الموظفون',
      'you': 'أنت',
      'anonymous_member': 'موظف',
      'position_of': 'من',
      'cycle_counts': 'جرود دورية',
      'full_counts': 'جرود عادية',
      'to_next_level': 'للمستوى التالي',
      'your_tasks': 'مهامك',
      'no_tasks': 'لا توجد مهام مستحقة 🎉',
      'start_now': 'ابدأ الآن',

      // Home
      'welcome': 'مرحباً 👋',
      // Smart home — Action Center + Your Day + greetings
      'action_center_title': 'ما يحتاج انتباهك الآن',
      'all_clear_title': 'كل شيء تمام 🎉',
      'all_clear_subtitle': 'لا توجد مهام عاجلة الآن',
      'greeting_morning': 'صباح الخير',
      'greeting_afternoon': 'مساء الخير',
      'greeting_evening': 'مساء الخير',
      'your_day': 'يومك',
      'your_day_start': 'ابدأ يومك',
      'your_day_start_hint': 'أنجز أول مهمة لتبدأ تقدّمك اليوم 🚀',
      'orders_fulfilled_today': 'طلبات جُهزت اليوم',
      'tasks_done_today': 'مهام أُنجزت اليوم',
      'cycle_progress': 'تقدّم الجرد الدوري',
      'sla_waiting_minutes': 'بانتظار {m} دقيقة',
      'feed_overdue': 'متأخر',
      'feed_overdue_f': 'متأخرة',
      'feed_due_today': 'مستحق اليوم',
      'feed_due_today_f': 'مستحقة اليوم',
      'feed_count_overdue': '{n} متأخرة',
      'quick_actions': 'الإجراءات السريعة',
      'stock_transfers': 'تحويلات المخزون',
      'start_new_count': 'بدء جرد جديد',
      'quick_look': 'نظرة سريعة',
      'transfers_pending_send': 'تحويلات بانتظار الإرسال',
      'transfers_pending_receive': 'تحويلات بانتظار الاستلام',
      'active_counting_sessions': 'سجلات جرد جارية',
      
      // Transfers
      'all': 'الكل',
      'status_new': 'جديد',
      'status_shipped': 'تم الشحن',
      'status_received': 'تم الاستلام',
      'status_partially_received': 'استلام جزئي',
      'status_completed': 'مكتمل',
      'status_cancelled': 'ملغي',
      'no_transfers': 'لا توجد تحويلات',
      'from': 'من',
      'to': 'إلى',
      'items': 'صنف',
      'sent': 'مرسل',
      // Transfers — tabs, filter & detail
      'tab_send': 'إرسال',
      'tab_receive': 'استلام',
      'transfers_send_empty': 'لا توجد تحويلات للإرسال',
      'transfers_receive_empty': 'لا توجد تحويلات للاستلام',
      'required_qty': 'المطلوب',
      'sent_qty': 'المرسل',
      'received_qty': 'المستلم',
      'items_count_label': 'الأصناف',
      'total_quantity': 'إجمالي الكمية',
      'transfer_date': 'التاريخ',
      'scan_to_confirm_send': 'مسح لتأكيد الإرسال',
      'scan_to_confirm_receive': 'مسح لتأكيد الاستلام',
      'confirm_send': 'تأكيد الإرسال',
      'confirm_receive': 'تأكيد الاستلام',
      'search': 'بحث',
      'search_transfers': 'البحث في التحويلات...',
      'search_counting': 'البحث في سجلات الجرد...',
      'no_results': 'لا توجد نتائج',
      
      // Counting
      'stock_counting': 'جرد المخزون',
      'new_count_btn': 'جرد جديد',
      'counting_in_progress': 'جاري الجرد',
      'no_sessions': 'لا توجد سجلات جرد',
      'click_to_start': 'اضغط على "جرد جديد" للبدء',
      'continue_counting': 'متابعة الجرد',
      'pieces': 'قطعة',
      'choose_warehouse': 'اختر المستودع',
      'cancel': 'إلغاء',
      'retry': 'إعادة المحاولة',
      'error_title': 'حدث خطأ',
      'error_subtitle': 'تعذر تحميل البيانات. تحقق من اتصالك بالإنترنت.',
      'barcode_scanner': 'سكان الباركود',
      'barcode_scanner_send': 'سكان تأكيد الإرسال',
      'barcode_scanner_receive': 'سكان تأكيد الاستلام',
      'quantity': 'الكمية',
      'update_quantity': 'تحديث الكمية',
      'add': 'إضافة',
      'product_not_in_transfer': 'المنتج غير موجود في التحويل',
      'skip_and_scan_next': 'تخطي وسكان التالي',
      'scanned_count': 'تم سكان {count} من {total} منتج',
      'unknown_product': 'منتج غير معروف',
      'product_saved': '✅ {name} — الكمية: {qty}',
      
      // Profile
      'phone': 'رقم الجوال',
      'warehouses': 'المستودعات',
      'roles': 'الأدوار',
      'version': 'الإصدار',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'notifications_title': 'الإشعارات',
      'notifications_subtitle': 'اختر قنوات تنبيهاتك',
      'notifications_hint': 'لكل تنبيه اختر القناة المناسبة: بريد، تطبيق، أو الاثنين.',
      'notifications_saved': 'تم حفظ التفضيلات',
      'notifications_save_failed': 'تعذّر الحفظ، حاول مجدداً',
      'notifications_empty': 'لا توجد تنبيهات قابلة للتخصيص لحسابك حالياً.',
      'channel_email': 'بريد',
      'channel_push': 'تطبيق',
      'channel_both': 'الاثنين',
      'language': 'اللغة / Language',
      'arabic': 'العربية',
      'english': 'English',
      'appearance': 'المظهر',
      'theme_system': 'حسب النظام',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'system_title': 'نظام إدارة المعارض - منتجات',

      // Promotions / Ad campaigns (owner only)
      'promotions': 'العروض',
      'promo_tab_suggested': 'مقترحة',
      'promo_tab_scheduled': 'مجدولة',
      'promo_tab_active': 'نشطة',
      'promo_tab_ended': 'منتهية',
      'no_promotions': 'لا توجد عروض حالياً',
      'promo_type_spotlight': 'الأكثر طلباً',
      'promo_type_clearance': 'تصفية',
      'promo_type_bundle': 'حزمة',
      'promo_type_new_arrival': 'وصل حديثاً',
      'promo_type_express': 'توصيل سريع',
      'offer_visibility': 'إبراز',
      'offer_coupon': 'كوبون',
      'offer_bundle': 'حزمة',
      'promo_creative': 'التصميم الإعلاني',
      'promo_copy': 'النص الإعلاني',
      'promo_headline': 'العنوان',
      'promo_subheadline': 'العنوان الفرعي',
      'promo_cta': 'زر الإجراء',
      'promo_offer': 'العرض',
      'promo_why': 'لماذا اقترحنا هذا؟',
      'rationale_capital': 'رأس المال المحتجَز',
      'rationale_cover': 'أيام التغطية',
      'rationale_rank': 'درجة الترتيب',
      'rationale_velocity': 'سرعة البيع',
      'rationale_fbt': 'قوة الاقتران',
      'rationale_in_stock': 'نسبة التوفّر',
      'rationale_stock': 'المخزون الحالي',
      'currency_sar': '\u{E900}',
      'unit_day': 'يوم',
      'unit_per_day': 'وحدة/يوم',
      'reason_help_title': 'لماذا اقترحنا هذا؟',
      'reason_help_how': 'كيف عرفنا ذلك؟',
      'reason_help_safe': 'هذا الاقتراح للإبراز فقط — لا يغيّر السعر ولا يكسر سعر الجملة. الخصومات (إن وُجدت) تحتاج موافقتك.',
      'reason_help_clearance': 'مخزون هذا المنتج كبير وحركته بطيئة، فجزء من رأس مالك محتجز فيه دون بيع. إبرازه إعلانياً يسرّع تدويره ويحرّر السيولة — بدون أي خصم، السعر يبقى محمياً.',
      'reason_help_spotlight': 'هذا من أقوى منتجاتك مبيعاً وأكثرها طلباً. إبرازه في مكان بارز يجذب الزيارات ويزيد المبيعات.',
      'reason_help_bundle': 'هذان المنتجان يُشتريان معاً كثيراً حسب تحليل سلال الشراء. عرضهما كباقة يرفع متوسّط قيمة السلة.',
      'reason_help_express': 'هذا المنتج متوفّر باستمرار وحركته جيدة، فهو مثالي لإبراز ميزة التوصيل السريع خلال ساعتين.',
      'reason_help_new_arrival': 'منتج جديد في الكتالوج. إبرازه يعرّف العملاء عليه بسرعة ويسرّع انطلاق مبيعاته.',
      'gloss_lps': 'نقاط أولوية التصفية — كل ما ارتفعت دلّت على مخزون أكبر وحركة أبطأ ورأس مال محتجز أكثر.',
      'gloss_capital': 'قيمة المخزون غير المُباع من هذا المنتج (التكلفة × الكمية المتبقية).',
      'gloss_cover': 'كم يوماً يكفي المخزون الحالي بمعدّل البيع الحالي — رقم كبير يعني ركوداً.',
      'gloss_rank': 'درجة مركّبة من المبيعات والربحية والتوفّر (من ١٠٠).',
      'gloss_velocity': 'متوسّط الوحدات المُباعة يومياً (مزيج آخر ٣٠ و٩٠ يوم).',
      'gloss_in_stock': 'نسبة الأيام التي كان فيها المنتج متوفّراً — قرب ١٠٠٪ يعني توفّراً ممتازاً.',
      'gloss_fbt': 'معامل الاقتران — كم مرة يُشترى المنتجان معاً مقارنةً بالصدفة.',
      'gloss_abc': 'تصنيف باريتو: A الأعلى مساهمة في المبيعات، ثم B ثم C.',
      'gloss_stock': 'عدد الوحدات المتوفّرة حالياً في المخزون.',
      'floor_safe': 'آمن — لا يقل عن سعر الجملة',
      'floor_breach': 'تحذير: السعر يقل عن حد الجملة — لا يمكن النشر',
      'promo_approve': 'موافقة ونشر',
      'promo_approve_place': 'اعتمِد وحدّد الموقع',
      'promo_publish': 'انشر',
      'promo_place_title': 'اختر موقع الإعلان',
      'promo_place_desc': 'وين يظهر هذا الإعلان في المتجر؟',
      'promo_approve_title': 'اعتماد العرض',
      'promo_place_section': 'موقع الإعلان',
      'design_identity_title': 'هوية التصميم',
      'design_identity_desc': 'نعتمد هوية البراند ولا هوية Zooboxi؟',
      'promo_generating_design': 'جاري توليد التصميم حسب الموقع…',
      'promo_no_image_yet': 'سيُولَّد التصميم بعد الاعتماد وتحديد الموقع',
      'promo_dismiss': 'تجاهل',
      'promo_dismissed': 'تم تجاهل الاقتراح',
      'promo_convert': 'حوّله لإعلان',
      'promo_open': 'اضغط للفتح',
      'promo_status_preview': 'معاينة',
      'promo_sig_lps': 'أولوية تصفية',
      'promo_sig_fbt': 'يُشترى معاً',
      'promo_sig_cover': 'تغطية',
      'promo_sig_rank': 'ترتيب',
      'promo_stage_concept': 'مفهوم',
      'promo_stage_preview': 'معاينة',
      'promo_stage_published': 'منشور',
      'promo_placement_home_banner_1': 'بانر الرئيسية ١',
      'promo_reject': 'رفض',
      'promo_regenerate': 'إعادة توليد',
      'promo_products': 'المنتجات في الإعلان',
      'promo_edit_ad': 'تعديل الإعلان',
      'promo_edit_desc': 'اكتب ملاحظتك على التصميم أو النص، وسيعيد الذكاء الاصطناعي توليد الصورة حسبها.',
      'promo_edit_hint': 'مثال: كبّر العنوان، خلفية أدفأ، أبرز الخصم أكثر…',
      'promo_edit_submit': 'عدّل بالذكاء الاصطناعي',
      'promo_refining': 'يُعاد توليد الإعلان حسب ملاحظتك…',
      'promo_reject_reason': 'سبب الرفض',
      'reject_cat_prompt': 'وش السبب الرئيسي للرفض؟ (يساعدنا نحسّن توليد الإعلانات)',
      'reject_cat_copy': 'النص والكتابة',
      'reject_cat_design': 'التصميم والألوان',
      'reject_cat_image': 'جودة الصورة',
      'reject_cat_product': 'المنتج غير مناسب',
      'reject_cat_offer': 'العرض غير مناسب',
      'reject_cat_identity': 'الشعار/الهوية',
      'reject_cat_other': 'أخرى',
      'reject_note_label': 'اشرح أكثر (اختياري)',
      'reject_note_hint': 'مثال: العنوان طويل، الخلفية مزدحمة، الشعار غير واضح…',
      'promo_published_done': 'تم نشر العرض في المتجر 🎉',
      'promo_approved_pending': 'تم الاعتماد',
      'promo_rejected': 'تم رفض العرض',
      'promo_regenerating': 'جارٍ إعادة توليد التصميم...',
      'publish_now': 'يُنشر فوراً عند الموافقة',

      // ─── لوحة الإدارة (Super Admin) ───
      'nav_admin': 'الإدارة',
      'admin_hub_title': 'لوحة الإدارة',
      'admin_hub_subtitle': 'أدوات المالك لإدارة المعارض',
      // ─── مركز القيادة (وضع المالك) ───
      'owner_nav_command': 'القيادة',
      'owner_nav_performance': 'الأداء',
      'owner_nav_logistics': 'المخزون والشحن',
      'owner_nav_logistics_short': 'اللوجستيات',
      'owner_nav_approvals': 'الموافقات',
      'owner_nav_profile': 'الملف',
      'owner_command_subtitle': 'نظرة شاملة على الشبكة',
      'owner_role_badge': 'المالك',
      'owner_greeting_morning': 'صباح الخير',
      'owner_greeting_noon': 'طاب يومك',
      'owner_greeting_evening': 'مساء الخير',
      'owner_net_sales_today': 'صافي مبيعات اليوم',
      'owner_net_unavailable': 'تعذّر تحميل المبيعات',
      'owner_section_pulse': 'نبض الشبكة',
      'owner_section_trend': 'المبيعات والأرباح',
      'owner_section_leaderboard': 'ترتيب الفروع',
      'owner_section_ops': 'الشحن والتوزيع',
      'owner_section_engine': 'محرّك التوزيع الذكي',
      'owner_section_containers': 'تنبيهات الشحن',
      'owner_kpi_profit': 'الربح',
      'owner_kpi_margin': 'الهامش',
      'owner_kpi_bleeding': 'نزيف شهري',
      'owner_kpi_trapped': 'رأس مال محتجز',
      'owner_kpi_branches': 'فروع نشطة',
      'owner_queue_title': 'ما ينتظر قرارك',
      'owner_queue_promos': 'عروض بانتظار الموافقة',
      'owner_queue_distribution': 'اقتراحات توزيع المخزون',
      'owner_queue_quality': 'مهام جودة متأخرة',
      'owner_queue_containers': 'حاويات تحتاج انتباه',
      'owner_queue_clear': 'لا قرارات معلّقة — كل شيء على ما يرام',
      'owner_engine_running': 'قيد التشغيل',
      'owner_engine_idle': 'خامل',
      'owner_engine_pending': 'اقتراح معلّق',
      'owner_containers_attention': 'تحتاج انتباه',
      'owner_containers_clear': 'لا تنبيهات شحن',
      'owner_load_error': 'تعذّر تحميل لوحة القيادة',
      'owner_logistics_subtitle': 'توزيع المخزون وتتبّع الحاويات',
      'owner_logistics_stock': 'التوزيع الذكي للمخزون',
      'owner_logistics_stock_sub': 'اقتراحات نقل المخزون بين الفروع',
      'owner_logistics_shipping': 'تتبّع الحاويات',
      'owner_logistics_shipping_sub': 'شحنات الاستيراد البحري الواردة',
      'owner_approvals_subtitle': 'ما يحتاج موافقتك قبل النشر',
      'owner_approvals_promos': 'العروض والإعلانات',
      'owner_approvals_promos_sub': 'حملات بانتظار موافقتك',
      'owner_approvals_quality': 'مهام الجودة',
      'owner_approvals_quality_sub': 'إدارة قوالب الجودة والمتابعة',
      'admin_retail_dashboard': 'لوحة البيع بالتجزئة',
      'admin_retail_dashboard_desc': 'أداء كل المعارض ومبيعاتها وصحتها',
      'admin_quality_tasks': 'إدارة مهام الجودة',
      'admin_quality_tasks_desc': 'إنشاء المهام ومتابعتها عبر المعارض',
      'admin_stock_distribution': 'التوزيع الذكي للمخزون',
      'admin_stock_distribution_desc': 'توصيات إعادة توزيع المخزون وتشغيل المحرك',
      'admin_container_tracking': 'تتبّع الحاويات',
      'admin_container_tracking_desc': 'شحنات الحاويات البحرية وحالة وصولها',

      // ─── Retail Dashboard ───
      'rd_title': 'لوحة البيع بالتجزئة',
      'rd_total_net': 'صافي المبيعات',
      'rd_total_invoices': 'الفواتير',
      'rd_branches_count': 'المعارض',
      'rd_period_today': 'اليوم',
      'rd_period_week': 'الأسبوع',
      'rd_period_month': 'الشهر',
      'rd_period_year': 'السنة',
      'rd_period_custom': 'مخصّص',
      'rd_sort_label': 'ترتيب حسب',
      'rd_sort_revenue': 'المبيعات',
      'rd_sort_score': 'النبض',
      'rd_sort_bleeding': 'النزيف',
      'rd_net_sales': 'صافي المبيعات',
      'rd_invoices': 'فاتورة',
      'rd_score': 'النبض',
      'rd_rank': 'الترتيب',
      'rd_bleeding': 'نزيف شهري',
      'rd_trapped': 'رأس مال محتجز',
      'rd_profit': 'ربح تقديري',
      'rd_profit_short': 'ربح',
      'rd_margin': 'هامش',
      'rd_sort_profit': 'الربح',
      'rd_sales_profit_chart': 'المبيعات والأرباح',
      'rd_profit_actual': 'ربح فعلي',
      'rd_profit_note': 'الربح تقديري بناءً على متوسط هامش الأصناف ذات التكلفة الموثوقة',
      'rd_profit_note_actual': 'ربح فعلي من فواتير SAP (التكلفة وقت البيع)',
      'rd_ops_pending': 'مهام معلّقة',
      'rd_no_branches': 'لا توجد معارض',
      'rd_channel_total': 'الإجمالي',
      'rd_channel_retail': 'المعارض',
      'rd_channel_wholesale': 'الجملة',
      'rd_top_customers': 'كبار عملاء الجملة',
      'rd_customers_count': 'عميل',
      'rd_no_customers': 'لا يوجد عملاء جملة في هذه الفترة',
      'rd_comparison_title': 'المعارض مقابل الجملة',
      'rd_invoices_short': 'فاتورة',
      'owner_total_sales_today': 'إجمالي مبيعات اليوم',
      'rd_no_data': 'لا توجد بيانات لهذه الفترة',

      // ─── Branch detail ───
      'bd_revenue': 'المبيعات',
      'bd_gross': 'الإجمالي',
      'bd_returns': 'المرتجعات',
      'bd_aov': 'متوسط السلة',
      'bd_trend': 'اتجاه المبيعات',
      'bd_peak': 'الأعلى:',
      'bd_top_products': 'الأكثر مبيعاً',
      'bd_units': 'وحدة',
      'bd_vitals': 'المؤشّرات الحيوية',
      'bd_levers': 'روافع المال',
      'bd_bleeding_title': 'أوقف النزيف',
      'bd_trapped_title': 'حرّر رأس المال',
      'bd_bleeding_sub': 'أصناف تخسر مبيعات بسبب نقص المخزون',
      'bd_trapped_sub': 'أصناف راكدة تحتجز رأس مالك',
      'bd_top_sub': 'الأكثر مبيعاً خلال الفترة',
      'rd_view_all': 'عرض الكل',
      'rd_remaining': 'المتبقي',
      'rd_lost_monthly': 'خسارة/شهر',
      'rd_capital_short': 'رأس مال',
      'rd_no_items': 'لا توجد أصناف',
      'rd_no_items_tab': 'لا يوجد أصناف في هذا التصنيف',
      'rd_tab_all': 'الكل',
      'rd_tab_oos': 'عاجل',
      'rd_tab_transfer': 'تحويل',
      'rd_tag_reorder': 'طلب مورد',
      'rd_tag_transfer': 'تحويل مخزون',
      'rd_tag_on_order': 'قيد الطلب',
      'health_stockout': 'نافد',
      'health_starved': 'شحيح',
      'health_low': 'منخفض',
      'health_overstock': 'فائض',
      'health_dead': 'راكد',
      'bd_ops': 'العمليات',
      'ops_quality': 'مهام الجودة',
      'ops_counting': 'جلسات الجرد',
      'ops_transfers': 'تحويلات جديدة',
      'ops_zooboxi': 'طلبات زوبوكسي',
      'vital_hero_availability': 'توفّر المنتجات البطلة',
      'vital_capital_efficiency': 'كفاءة رأس المال',
      'vital_basket_size': 'حجم السلة',
      'vital_count_accuracy': 'دقة الجرد',

      // ─── Quality Tasks admin ───
      'qa_title': 'إدارة مهام الجودة',
      'qa_tab_templates': 'القوالب',
      'qa_tab_followup': 'المتابعة',
      'qa_create': 'مهمة جديدة',
      'qa_pending': 'معلّقة',
      'qa_submitted': 'منجزة',
      'qa_overdue': 'متأخرة',
      'qa_active': 'مفعّلة',
      'qa_inactive': 'معطّلة',
      'qa_no_templates': 'لا توجد قوالب',
      'qa_no_instances': 'لا توجد نسخ',
      'qa_generate_now': 'توليد الآن',
      'qa_generated_done': 'تم إنشاء النسخة',
      'qa_recurrence': 'التكرار',
      'rec_once': 'مهمة فورية (مرة واحدة)',
      'rec_daily': 'يومي',
      'rec_weekly': 'أسبوعي',
      'qa_proof_type': 'نوع الإثبات',
      'qa_title_label': 'عنوان المهمة',
      'qa_description_label': 'الوصف (اختياري)',
      'qa_min_photos': 'أقل عدد للصور',
      'qa_require_comment': 'طلب تعليق',
      'qa_checklist_items': 'بنود القائمة',
      'qa_add_item': 'إضافة بند',
      'qa_item_label': 'نص البند',
      'qa_item_require_photo': 'يتطلّب صورة',
      'qa_days_of_week': 'أيام الأسبوع',
      'qa_priority': 'الأولوية',
      'priority_high': 'عالية',
      'priority_medium': 'متوسطة',
      'priority_low': 'منخفضة',
      'qa_warehouses': 'المعارض',
      'qa_select_warehouses': 'اختر المعارض',
      'qa_save': 'حفظ المهمة',
      'qa_created_done': 'تم إنشاء المهمة',
      'qa_select_warehouse_first': 'اختر معرضاً واحداً على الأقل',
      'qs_content': 'محتوى المهمة',
      'qs_notes': 'ملاحظات المنفّذ',
      'qs_no_photos': 'لا توجد صور مرفقة',
      'qs_acknowledged': 'تم الإقرار بالمهمة',
      'qs_photos_count': 'صورة',
      'qs_tap_to_view': 'اضغط لعرض الصور',

      // ─── Stock Distribution ───
      'sd_title': 'التوزيع الذكي للمخزون',
      'sd_run_engine': 'تشغيل المحرك',
      'sd_running': 'جارٍ حساب التوصيات…',
      'sd_run_started': 'بدأ تشغيل المحرك، سيتم التحديث عند الانتهاء',
      'sd_last_run': 'آخر تشغيل',
      'sd_pending_count': 'توصية معلّقة',
      'sd_central': 'من مستودع مركزي',
      'sd_cross_dock': 'مناقلة بين المعارض',
      'sd_no_suggestions': 'لا توجد توصيات حالياً',
      'sd_units': 'وحدة',
      'sd_qty': 'الكمية المقترحة',
      'sd_source': 'المصدر',
      'sd_target': 'الوجهة',
      'sd_never_run': 'لم يُشغّل بعد',
      'sd_from': 'من',
      'sd_to': 'إلى',
      'sd_type': 'النوع',
      'sd_all': 'الكل',
      'sd_central_short': 'مركزي',
      'sd_cross_dock_short': 'عرضي',
      'sd_no_match': 'لا توجد توصيات مطابقة للفلاتر',
      'sd_reset': 'مسح الفلاتر',
      'sd_at_source': 'بالمصدر',
      'sd_lane': 'مسار',

      // ─── تتبّع الحاويات (Container Tracking) ───
      'ct_title': 'تتبّع الحاويات',
      'ct_subtitle': 'الشحنات البحرية القادمة',
      'ct_search_hint': 'ابحث برقم الحاوية أو الميناء أو الناقل…',
      'ct_filter_all': 'الكل',
      'ct_filter_overdue': 'متأخرة',
      'ct_filter_arriving': 'تصل قريباً',
      'ct_filter_in_transit': 'في الطريق',
      'ct_filter_pending': 'قيد التهيئة',
      'ct_filter_delivered': 'وصلت',
      'ct_sort_urgency': 'الأهمية',
      'ct_sort_eta': 'الأقرب وصولاً',
      'ct_sort_added': 'الأحدث',
      'ct_attention': 'تحتاج متابعة',
      'ct_nearest': 'أقرب وصول',
      'ct_in_transit_count': 'في الطريق',
      'ct_no_containers': 'لا توجد حاويات مطابقة',
      'ct_last_synced': 'آخر تحديث',
      'ct_carrier': 'الناقل',
      'ct_eta': 'الوصول المتوقع',
      'ct_ship_date': 'تاريخ الشحن',
      'ct_reference': 'رقم الحاوية',
      'ct_boxes': 'حاوية',
      'ct_eta_changed': 'تغيّر موعد الوصول',
      'ct_eta_changed_times': 'مرّة',
      'ct_voyage': 'مسار الرحلة',
      'ct_events': 'سجل التتبّع',
      'ct_no_events': 'لا توجد أحداث تتبّع بعد',
      'ct_vessel': 'السفينة الحالية',
      'ct_siblings': 'حاويات في نفس الشحنة',
      'ct_open_traqo': 'نسخ رابط التتبّع',
      'ct_link_copied': 'تم نسخ رابط التتبّع',
      'ct_progress': 'تقدّم الرحلة',
    },
    'en': {
      'app_title': 'Muntajat HUB',
      'app_subtitle': 'Branches & Showrooms',

      // Auth
      'login': 'Login',
      'login_subtitle': 'Enter login details to continue',
      'email': 'Email Address',
      'email_hint': 'example@muntajat.sa',
      'password': 'Password',
      'password_required': 'Please enter password',
      'email_required': 'Please enter email address',
      'email_invalid': 'Invalid email address',
      'unexpected_error': 'An unexpected error occurred',

      // Public landing (pre-login)
      'landing_welcome': 'Welcome to',
      'company_news': 'Company News',
      'about_company': 'About',
      'news_empty': 'No news yet',
      'loading_error': "Couldn't load content, please try again",
      'read_more': 'Read more',
      'our_brands': 'Our Brands',
      'our_branches': 'Our Branches',
      'directions': 'Directions',
      'branch_call': 'Call',
      'brand_products': 'Products',
      'brand_no_products': 'No product images yet',
      'brand_founded': 'Founded',
      'brand_origin': 'Origin',
      'landing_news': 'Latest News',
      'stat_brands': 'Brands',
      'stat_branches': 'Branches',
      'stat_cities': 'Cities',
      'brand_products_unit': 'products',
      'landing_footer_tag': 'The Kingdom\'s leading distributor of top brands',
      'news_tag': 'News',
      'brand_featured': 'Featured',
      'tap_to_view': 'Tap to view',
      'all_label': 'All',

      // OTP / phone login
      'login_with_email': 'Email & Password',
      'login_with_phone': 'By Phone',
      'mobile_number': 'Mobile number',
      'mobile_number_hint': '05XXXXXXXX',
      'mobile_required': 'Please enter mobile number',
      'otp_login_hint': "We'll send you a verification code via SMS",
      'send_otp': 'Send code',
      'otp_sent_to': 'A verification code was sent to',
      'enter_otp': 'Enter verification code',
      'verify': 'Verify & sign in',
      'resend_otp': 'Resend code',
      'resend_in': 'Resend in {s}s',
      'otp_invalid': 'Invalid or expired code',
      'mobile_not_registered': 'Mobile number not registered. Contact admin.',
      'change_number': 'Change number',
      
      // Bottom Nav
      'nav_home': 'Home',
      'nav_showroom_pulse': 'Pulse',
      'showroom_pulse_title': 'Showroom Pulse',
      'nav_transfers': 'Transfers',
      'nav_counting': 'Counting',
      'nav_achievements': 'Rewards',
      'nav_profile': 'Profile',

      // Achievements / Gamification
      'achievements_subtitle': 'Your points, badges & rank',
      'achievements_soon_title': 'Your rewards are coming soon',
      'achievements_soon_subtitle': 'Complete counting tasks to earn points and badges',

      // Cycle Counting (guided)
      'cycle_count': 'Cycle Count',
      'full_count': 'Annual Count',
      'status_filter_title': 'Filter by status',
      'items_to_count': 'Items to Count',
      'counted': 'Counted',
      'pending_count': 'Pending',
      'remaining_items': 'remaining',
      'scan_to_count': 'Scan',
      'complete_count': 'Complete Count',
      'scan_at_least_one': 'Scan at least one item to complete',
      'count_completed': 'Count completed 🎉',
      'cycle_auto_generated': 'Cycle tasks are generated automatically each week',
      'no_targets': 'No target items in this task',
      'class_label': 'Class',
      'overdue_label': 'Overdue',
      'due_label': 'Due',

      // Cycle detail — tabs & records
      'cycle_targets_tab': 'Targets',
      'cycle_records_tab': 'My Records',
      'counted_records': 'Entered Records',
      'no_records_yet': 'No records entered yet',
      'no_records_yet_hint': 'Scan items to log your counts',
      'entry_n': 'Entry {n}',
      'counted_products_n': 'Counted Products ({n})',
      'edit_quantity': 'Edit Quantity',
      'delete_record': 'Delete Record',
      'delete_record_confirm': 'Delete this record from the count?',
      'update': 'Update',
      'delete': 'Delete',
      // Off-list scanner gating (cycle)
      'off_list_title': 'Off-list item',
      'product_off_cycle_list': 'This product is not in the cycle-count list',
      'off_list_cannot_count': "Off-list items can't be counted",
      'off_list_scans_n': '{n} off-list scan(s)',
      'counted_label': 'counted',

      // Quality Control
      'quality_tasks': 'Quality Tasks',
      'quality_section_subtitle': 'Due today',
      'no_quality_tasks': 'No quality tasks 🎉',
      'view_all': 'View all',
      'status_pending': 'Pending',
      'status_submitted': 'Done',
      'proof_acknowledge': 'Confirm',
      'proof_photo': 'Photos',
      'proof_checklist': 'Checklist',
      'mark_done': 'Mark Done',
      'submit_task': 'Submit',
      'task_submitted': 'Task completed 🎉',
      'add_photo': 'Add photo',
      'take_photo': 'Take photo',
      'choose_from_gallery': 'From gallery',
      'photos_progress': '{x} / {min} photos',
      'comment_optional': 'Comment (optional)',
      'comment_required_label': 'Comment (required)',
      'complete_all_items': 'Complete all items to submit',
      'photo_required_badge': 'Photo required',
      'acknowledge_hint': 'Tap to confirm when the task is done',
      'overdue_badge': 'Overdue',

      // Zooboxi Express Orders
      'zooboxi_urgent_orders': 'Zooboxi Urgent Orders',
      'zooboxi_section_subtitle': 'Express orders awaiting preparation',
      'no_urgent_orders': 'No urgent orders 🎉',
      'orders_new': 'New',
      'orders_waiting': 'Waiting',
      'orders_done': 'Done',
      'no_done_orders': 'No prepared orders yet',
      'status_done': 'Done',
      'nav_zooboxi': 'Urgent',
      'status_preparing': 'Preparing',
      'order_no': 'Order',
      'order_items': 'Items',
      'express_delivery': 'Express',
      'qty_short': 'Qty',
      'currency': '\u{E900}',
      'minutes_ago': '{x} min ago',
      'hours_ago': '{x} h ago',
      'start_preparing': 'Start Preparing',
      'mark_prepared': 'Mark Prepared',
      'order_prepared_done': 'Order prepared ✓',
      'order_prepared_no_sync': 'Prepared ✓ — store update failed, will sync later',

      // Gamification detail
      'points': 'points',
      'level': 'Level',
      'streak': 'Streak',
      'weeks': 'weeks',
      'accuracy': 'Accuracy',
      'this_month': 'This month',
      'weekly_goal': 'Weekly Goal',
      'leaderboard': 'Leaderboard',
      'rank_branch': 'Branch rank',
      'rank_in_branch': 'Rank in branch',
      'rank_company': 'Company rank',
      'badges_title': 'Badges',
      'branches': 'Branches',
      'employees': 'Employees',
      'you': 'You',
      'anonymous_member': 'Member',
      'position_of': 'of',
      'cycle_counts': 'Cycle counts',
      'full_counts': 'Full counts',
      'to_next_level': 'to next level',
      'your_tasks': 'Your Tasks',
      'no_tasks': 'No due tasks 🎉',
      'start_now': 'Start now',

      // Home
      'welcome': 'Welcome 👋',
      // Smart home — Action Center + Your Day + greetings
      'action_center_title': 'Needs your attention',
      'all_clear_title': 'All clear 🎉',
      'all_clear_subtitle': 'Nothing urgent right now',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'your_day': 'Your day',
      'your_day_start': 'Start your day',
      'your_day_start_hint': 'Finish your first task to kick off today 🚀',
      'orders_fulfilled_today': 'Orders fulfilled today',
      'tasks_done_today': 'Tasks done today',
      'cycle_progress': 'Cycle progress',
      'sla_waiting_minutes': 'Waiting {m} min',
      'feed_overdue': 'Overdue',
      'feed_overdue_f': 'Overdue',
      'feed_due_today': 'Due today',
      'feed_due_today_f': 'Due today',
      'feed_count_overdue': '{n} overdue',
      'quick_actions': 'Quick Actions',
      'stock_transfers': 'Stock Transfers',
      'start_new_count': 'New Count',
      'quick_look': 'Quick Look',
      'transfers_pending_send': 'Pending Send',
      'transfers_pending_receive': 'Pending Receive',
      'active_counting_sessions': 'Active Counts',
      
      // Transfers
      'all': 'All',
      'status_new': 'New',
      'status_shipped': 'Shipped',
      'status_received': 'Received',
      'status_partially_received': 'Partially Received',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'no_transfers': 'No transfers found',
      'from': 'From',
      'to': 'To',
      'items': 'Items',
      'sent': 'Sent',
      // Transfers — tabs, filter & detail
      'tab_send': 'Send',
      'tab_receive': 'Receive',
      'transfers_send_empty': 'No transfers to send',
      'transfers_receive_empty': 'No transfers to receive',
      'required_qty': 'Required',
      'sent_qty': 'Sent',
      'received_qty': 'Received',
      'items_count_label': 'Items',
      'total_quantity': 'Total Qty',
      'transfer_date': 'Date',
      'scan_to_confirm_send': 'Scan to confirm send',
      'scan_to_confirm_receive': 'Scan to confirm receive',
      'confirm_send': 'Confirm Send',
      'confirm_receive': 'Confirm Receive',
      'search': 'Search',
      'search_transfers': 'Search transfers...',
      'search_counting': 'Search counting sessions...',
      'no_results': 'No results found',
      
      // Counting
      'stock_counting': 'Stock Counting',
      'new_count_btn': 'New Count',
      'counting_in_progress': 'In Progress',
      'no_sessions': 'No counting sessions',
      'click_to_start': 'Click "New Count" to start',
      'continue_counting': 'Continue Count',
      'pieces': 'Pcs',
      'choose_warehouse': 'Choose Warehouse',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'error_title': 'Something went wrong',
      'error_subtitle': 'Could not load data. Please check your internet connection.',
      'barcode_scanner': 'Barcode Scanner',
      'barcode_scanner_send': 'Send Confirmation Scanner',
      'barcode_scanner_receive': 'Receive Confirmation Scanner',
      'quantity': 'Quantity',
      'update_quantity': 'Update Quantity',
      'add': 'Add',
      'product_not_in_transfer': 'Product not in this transfer',
      'skip_and_scan_next': 'Skip & Scan Next',
      'scanned_count': 'Scanned {count} of {total} items',
      'unknown_product': 'Unknown Product',
      'product_saved': '✅ {name} — Qty: {qty}',
      
      // Profile
      'phone': 'Mobile Number',
      'warehouses': 'Warehouses',
      'roles': 'Roles',
      'version': 'Version',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'notifications_title': 'Notifications',
      'notifications_subtitle': 'Choose your alert channels',
      'notifications_hint': 'For each alert, choose the channel: email, app, or both.',
      'notifications_saved': 'Preferences saved',
      'notifications_save_failed': 'Could not save, please retry',
      'notifications_empty': 'No configurable notifications for your account yet.',
      'channel_email': 'Email',
      'channel_push': 'App',
      'channel_both': 'Both',
      'language': 'Language / اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'appearance': 'Appearance',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'system_title': 'Exhibition Management System',

      // Promotions / Ad campaigns (owner only)
      'promotions': 'Promotions',
      'promo_tab_suggested': 'Suggested',
      'promo_tab_scheduled': 'Scheduled',
      'promo_tab_active': 'Active',
      'promo_tab_ended': 'Ended',
      'no_promotions': 'No promotions yet',
      'promo_type_spotlight': 'Top seller',
      'promo_type_clearance': 'Clearance',
      'promo_type_bundle': 'Bundle',
      'promo_type_new_arrival': 'New arrival',
      'promo_type_express': 'Express',
      'offer_visibility': 'Spotlight',
      'offer_coupon': 'Coupon',
      'offer_bundle': 'Bundle',
      'promo_creative': 'Ad creative',
      'promo_copy': 'Ad copy',
      'promo_headline': 'Headline',
      'promo_subheadline': 'Subheadline',
      'promo_cta': 'Call to action',
      'promo_offer': 'Offer',
      'promo_why': 'Why suggested?',
      'rationale_capital': 'Capital at risk',
      'rationale_cover': 'Days of cover',
      'rationale_rank': 'Rank score',
      'rationale_velocity': 'Sales velocity',
      'rationale_fbt': 'Affinity (lift)',
      'rationale_in_stock': 'In-stock rate',
      'rationale_stock': 'Current stock',
      'currency_sar': '\u{E900}',
      'unit_day': 'days',
      'unit_per_day': 'units/day',
      'reason_help_title': 'Why we suggested this',
      'reason_help_how': 'How we know',
      'reason_help_safe': 'This suggestion is visibility-only — it never changes the price or breaks the wholesale floor. Any discount needs your approval.',
      'reason_help_clearance': 'This product is overstocked and slow-moving, so part of your capital is locked in unsold inventory. Promoting it speeds up turnover and frees cash — with no discount; the price stays protected.',
      'reason_help_spotlight': 'This is one of your strongest, most in-demand sellers. Featuring it prominently drives traffic and lifts sales.',
      'reason_help_bundle': 'These two products are frequently bought together (basket analysis). Offering them as a bundle raises the average cart value.',
      'reason_help_express': 'This product is consistently in stock and sells well — ideal for highlighting the 2-hour express delivery.',
      'reason_help_new_arrival': 'A new product in the catalog. Featuring it introduces it to customers quickly and jump-starts its sales.',
      'gloss_lps': 'Liquidation Priority Score — higher means more stock, slower movement and more tied-up capital.',
      'gloss_capital': 'Value of the unsold inventory for this product (cost × remaining quantity).',
      'gloss_cover': 'How many days the current stock lasts at the current sales rate — high means stagnant.',
      'gloss_rank': 'A composite score from sales, profitability and availability (out of 100).',
      'gloss_velocity': 'Average units sold per day (blend of the last 30 and 90 days).',
      'gloss_in_stock': 'Share of days the product was in stock — near 100% means excellent availability.',
      'gloss_fbt': 'Affinity lift — how many times more often the two are bought together vs. chance.',
      'gloss_abc': 'Pareto class: A contributes most to sales, then B, then C.',
      'gloss_stock': 'Units currently available in inventory.',
      'floor_safe': 'Safe — not below wholesale price',
      'floor_breach': 'Warning: below wholesale floor — cannot publish',
      'promo_approve': 'Approve & publish',
      'promo_approve_place': 'Approve & place',
      'promo_publish': 'Publish',
      'promo_place_title': 'Choose ad placement',
      'promo_place_desc': 'Where should this ad appear in the store?',
      'promo_approve_title': 'Approve offer',
      'promo_place_section': 'Ad placement',
      'design_identity_title': 'Design identity',
      'design_identity_desc': 'Use the brand identity or Zooboxi?',
      'promo_generating_design': 'Generating the design for this placement…',
      'promo_no_image_yet': 'The design is generated after you approve and pick a placement',
      'promo_dismiss': 'Dismiss',
      'promo_dismissed': 'Suggestion dismissed',
      'promo_convert': 'Turn into ad',
      'promo_open': 'Open',
      'promo_status_preview': 'Preview',
      'promo_sig_lps': 'Clearance priority',
      'promo_sig_fbt': 'Bought together',
      'promo_sig_cover': 'Cover',
      'promo_sig_rank': 'Rank',
      'promo_stage_concept': 'Concept',
      'promo_stage_preview': 'Preview',
      'promo_stage_published': 'Published',
      'promo_placement_home_banner_1': 'Home banner 1',
      'promo_reject': 'Reject',
      'promo_regenerate': 'Regenerate',
      'promo_products': 'Products in the ad',
      'promo_edit_ad': 'Edit ad',
      'promo_edit_desc': 'Write a note about the design or text and the AI will re-render the image accordingly.',
      'promo_edit_hint': 'e.g. bigger headline, warmer background, emphasize the discount…',
      'promo_edit_submit': 'Edit with AI',
      'promo_refining': 'Re-rendering the ad to your note…',
      'promo_reject_reason': 'Reject reason',
      'reject_cat_prompt': 'Main reason for rejecting? (helps us improve ad generation)',
      'reject_cat_copy': 'Text & copy',
      'reject_cat_design': 'Design & colors',
      'reject_cat_image': 'Image quality',
      'reject_cat_product': 'Wrong product',
      'reject_cat_offer': 'Offer not suitable',
      'reject_cat_identity': 'Logo / identity',
      'reject_cat_other': 'Other',
      'reject_note_label': 'Explain more (optional)',
      'reject_note_hint': 'e.g. headline too long, busy background, logo unclear…',
      'promo_published_done': 'Published to the store 🎉',
      'promo_approved_pending': 'Approved',
      'promo_rejected': 'Campaign rejected',
      'promo_regenerating': 'Regenerating creative...',
      'publish_now': 'Publishes immediately on approval',

      // ─── Admin hub (Super Admin) ───
      'nav_admin': 'Admin',
      'admin_hub_title': 'Admin Center',
      'admin_hub_subtitle': 'Owner tools for managing exhibitions',
      // ─── Command Center (owner mode) ───
      'owner_nav_command': 'Command',
      'owner_nav_performance': 'Performance',
      'owner_nav_logistics': 'Stock & Shipping',
      'owner_nav_logistics_short': 'Logistics',
      'owner_nav_approvals': 'Approvals',
      'owner_nav_profile': 'Profile',
      'owner_command_subtitle': 'A network-wide overview',
      'owner_role_badge': 'Owner',
      'owner_greeting_morning': 'Good morning',
      'owner_greeting_noon': 'Good day',
      'owner_greeting_evening': 'Good evening',
      'owner_net_sales_today': "Today's net sales",
      'owner_net_unavailable': 'Sales unavailable',
      'owner_section_pulse': 'Network pulse',
      'owner_section_trend': 'Sales & profit',
      'owner_section_leaderboard': 'Branch ranking',
      'owner_section_ops': 'Shipping & distribution',
      'owner_section_engine': 'Smart distribution engine',
      'owner_section_containers': 'Shipping alerts',
      'owner_kpi_profit': 'Profit',
      'owner_kpi_margin': 'Margin',
      'owner_kpi_bleeding': 'Monthly bleed',
      'owner_kpi_trapped': 'Trapped capital',
      'owner_kpi_branches': 'Active branches',
      'owner_queue_title': 'Awaiting your decision',
      'owner_queue_promos': 'Promotions pending approval',
      'owner_queue_distribution': 'Stock distribution suggestions',
      'owner_queue_quality': 'Overdue quality tasks',
      'owner_queue_containers': 'Containers needing attention',
      'owner_queue_clear': 'Nothing pending — all clear',
      'owner_engine_running': 'Running',
      'owner_engine_idle': 'Idle',
      'owner_engine_pending': 'pending',
      'owner_containers_attention': 'need attention',
      'owner_containers_clear': 'No shipping alerts',
      'owner_load_error': 'Could not load the command center',
      'owner_logistics_subtitle': 'Stock distribution & container tracking',
      'owner_logistics_stock': 'Smart Stock Distribution',
      'owner_logistics_stock_sub': 'Suggested stock moves between branches',
      'owner_logistics_shipping': 'Container Tracking',
      'owner_logistics_shipping_sub': 'Inbound ocean-freight shipments',
      'owner_approvals_subtitle': 'What needs your approval before publishing',
      'owner_approvals_promos': 'Promotions & ads',
      'owner_approvals_promos_sub': 'Campaigns awaiting your approval',
      'owner_approvals_quality': 'Quality tasks',
      'owner_approvals_quality_sub': 'Manage quality templates & follow-up',
      'admin_retail_dashboard': 'Retail Dashboard',
      'admin_retail_dashboard_desc': 'Sales, health & performance across all stores',
      'admin_quality_tasks': 'Quality Tasks Admin',
      'admin_quality_tasks_desc': 'Create & follow up tasks across stores',
      'admin_stock_distribution': 'Smart Stock Distribution',
      'admin_stock_distribution_desc': 'Redistribution suggestions & run the engine',
      'admin_container_tracking': 'Container Tracking',
      'admin_container_tracking_desc': 'Ocean-freight shipments & their arrival status',

      // ─── Retail Dashboard ───
      'rd_title': 'Retail Dashboard',
      'rd_total_net': 'Net Sales',
      'rd_total_invoices': 'Invoices',
      'rd_branches_count': 'Stores',
      'rd_period_today': 'Today',
      'rd_period_week': 'Week',
      'rd_period_month': 'Month',
      'rd_period_year': 'Year',
      'rd_period_custom': 'Custom',
      'rd_sort_label': 'Sort by',
      'rd_sort_revenue': 'Sales',
      'rd_sort_score': 'Pulse',
      'rd_sort_bleeding': 'Bleeding',
      'rd_net_sales': 'Net Sales',
      'rd_invoices': 'invoices',
      'rd_score': 'Pulse',
      'rd_rank': 'Rank',
      'rd_bleeding': 'Monthly bleed',
      'rd_trapped': 'Trapped capital',
      'rd_profit': 'Est. profit',
      'rd_profit_short': 'Profit',
      'rd_margin': 'Margin',
      'rd_sort_profit': 'Profit',
      'rd_sales_profit_chart': 'Sales & Profit',
      'rd_profit_actual': 'Actual profit',
      'rd_profit_note': 'Profit is estimated from the average margin of items with reliable cost',
      'rd_profit_note_actual': 'Actual profit from SAP invoices (cost at sale)',
      'rd_ops_pending': 'pending tasks',
      'rd_no_branches': 'No stores',
      'rd_channel_total': 'Total',
      'rd_channel_retail': 'Showrooms',
      'rd_channel_wholesale': 'Wholesale',
      'rd_top_customers': 'Top wholesale customers',
      'rd_customers_count': 'customers',
      'rd_no_customers': 'No wholesale customers this period',
      'rd_comparison_title': 'Showrooms vs wholesale',
      'rd_invoices_short': 'inv.',
      'owner_total_sales_today': "Today's total sales",
      'rd_no_data': 'No data for this period',

      // ─── Branch detail ───
      'bd_revenue': 'Sales',
      'bd_gross': 'Gross',
      'bd_returns': 'Returns',
      'bd_aov': 'Avg basket',
      'bd_trend': 'Sales trend',
      'bd_peak': 'Peak',
      'bd_top_products': 'Top sellers',
      'bd_units': 'units',
      'bd_vitals': 'Vital signs',
      'bd_levers': 'Money levers',
      'bd_bleeding_title': 'Stop the bleeding',
      'bd_trapped_title': 'Free your cash',
      'bd_bleeding_sub': 'Items losing sales to low stock',
      'bd_trapped_sub': 'Stagnant items tying up your cash',
      'bd_top_sub': 'Best-sellers for the period',
      'rd_view_all': 'View all',
      'rd_remaining': 'Left',
      'rd_lost_monthly': 'Lost/mo',
      'rd_capital_short': 'Capital',
      'rd_no_items': 'No items',
      'rd_no_items_tab': 'No items in this group',
      'rd_tab_all': 'All',
      'rd_tab_oos': 'Urgent',
      'rd_tab_transfer': 'Transfer',
      'rd_tag_reorder': 'Reorder',
      'rd_tag_transfer': 'Transfer',
      'rd_tag_on_order': 'On order',
      'health_stockout': 'Out',
      'health_starved': 'Starved',
      'health_low': 'Low',
      'health_overstock': 'Excess',
      'health_dead': 'Dead',
      'bd_ops': 'Operations',
      'ops_quality': 'Quality tasks',
      'ops_counting': 'Counting sessions',
      'ops_transfers': 'New transfers',
      'ops_zooboxi': 'Zooboxi orders',
      'vital_hero_availability': 'Hero availability',
      'vital_capital_efficiency': 'Capital efficiency',
      'vital_basket_size': 'Basket size',
      'vital_count_accuracy': 'Count accuracy',

      // ─── Quality Tasks admin ───
      'qa_title': 'Quality Tasks Admin',
      'qa_tab_templates': 'Templates',
      'qa_tab_followup': 'Follow-up',
      'qa_create': 'New task',
      'qa_pending': 'Pending',
      'qa_submitted': 'Done',
      'qa_overdue': 'Overdue',
      'qa_active': 'Active',
      'qa_inactive': 'Inactive',
      'qa_no_templates': 'No templates',
      'qa_no_instances': 'No instances',
      'qa_generate_now': 'Generate now',
      'qa_generated_done': 'Instance created',
      'qa_recurrence': 'Recurrence',
      'rec_once': 'Immediate (one-off)',
      'rec_daily': 'Daily',
      'rec_weekly': 'Weekly',
      'qa_proof_type': 'Proof type',
      'qa_title_label': 'Task title',
      'qa_description_label': 'Description (optional)',
      'qa_min_photos': 'Min photos',
      'qa_require_comment': 'Require comment',
      'qa_checklist_items': 'Checklist items',
      'qa_add_item': 'Add item',
      'qa_item_label': 'Item text',
      'qa_item_require_photo': 'Requires photo',
      'qa_days_of_week': 'Days of week',
      'qa_priority': 'Priority',
      'priority_high': 'High',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      'qa_warehouses': 'Stores',
      'qa_select_warehouses': 'Select stores',
      'qa_save': 'Save task',
      'qa_created_done': 'Task created',
      'qa_select_warehouse_first': 'Select at least one store',
      'qs_content': 'Task content',
      'qs_notes': 'Notes',
      'qs_no_photos': 'No photos attached',
      'qs_acknowledged': 'Task acknowledged',
      'qs_photos_count': 'photos',
      'qs_tap_to_view': 'Tap to view photos',

      // ─── Stock Distribution ───
      'sd_title': 'Smart Stock Distribution',
      'sd_run_engine': 'Run engine',
      'sd_running': 'Computing suggestions…',
      'sd_run_started': 'Engine started, will refresh when done',
      'sd_last_run': 'Last run',
      'sd_pending_count': 'pending suggestions',
      'sd_central': 'From central warehouse',
      'sd_cross_dock': 'Cross-dock between stores',
      'sd_no_suggestions': 'No suggestions right now',
      'sd_units': 'units',
      'sd_qty': 'Suggested qty',
      'sd_source': 'Source',
      'sd_target': 'Target',
      'sd_never_run': 'Never run yet',
      'sd_from': 'From',
      'sd_to': 'To',
      'sd_type': 'Type',
      'sd_all': 'All',
      'sd_central_short': 'Central',
      'sd_cross_dock_short': 'Cross-dock',
      'sd_no_match': 'No suggestions match the filters',
      'sd_reset': 'Reset filters',
      'sd_at_source': 'at source',
      'sd_lane': 'lanes',

      // ─── Container Tracking ───
      'ct_title': 'Container Tracking',
      'ct_subtitle': 'Incoming ocean-freight shipments',
      'ct_search_hint': 'Search container, port or carrier…',
      'ct_filter_all': 'All',
      'ct_filter_overdue': 'Overdue',
      'ct_filter_arriving': 'Arriving',
      'ct_filter_in_transit': 'In transit',
      'ct_filter_pending': 'Pending',
      'ct_filter_delivered': 'Delivered',
      'ct_sort_urgency': 'Urgency',
      'ct_sort_eta': 'Soonest',
      'ct_sort_added': 'Newest',
      'ct_attention': 'Need attention',
      'ct_nearest': 'Nearest arrival',
      'ct_in_transit_count': 'In transit',
      'ct_no_containers': 'No matching containers',
      'ct_last_synced': 'Last updated',
      'ct_carrier': 'Carrier',
      'ct_eta': 'ETA',
      'ct_ship_date': 'Ship date',
      'ct_reference': 'Container',
      'ct_boxes': 'boxes',
      'ct_eta_changed': 'ETA changed',
      'ct_eta_changed_times': 'time(s)',
      'ct_voyage': 'Voyage',
      'ct_events': 'Tracking log',
      'ct_no_events': 'No tracking events yet',
      'ct_vessel': 'Current vessel',
      'ct_siblings': 'Containers in same shipment',
      'ct_open_traqo': 'Copy tracking link',
      'ct_link_copied': 'Tracking link copied',
      'ct_progress': 'Voyage progress',
    }
  };

  /// Translate a key based on current locale
  static String translate(String key) {
    final language = localeNotifier.value.languageCode;
    return _localizedValues[language]?[key] ?? key;
  }

  /// Initialize and load stored locale from SecureStorage
  static Future<void> initialize() async {
    final savedLanguage = await SecureStorage.read(_localeStorageKey);
    if (savedLanguage != null && _localizedValues.containsKey(savedLanguage)) {
      localeNotifier.value = Locale(savedLanguage);
    }
  }

  /// Change active language and persist to SecureStorage
  static Future<void> toggleLanguage() async {
    final nextLang = isArabic ? 'en' : 'ar';
    localeNotifier.value = Locale(nextLang);
    await SecureStorage.write(_localeStorageKey, nextLang);
  }
}

/// Inherited locale boundary placed **above the Navigator** (in `MaterialApp.builder`).
///
/// Reading a string with [BuildContext.tr] registers a dependency on this
/// widget, so when the language changes every screen that shows text — including
/// already-pushed routes — rebuilds and re-translates. Without it, only the
/// global `Directionality` flipped (layout mirrored) while strings stayed stale.
class LocaleScope extends InheritedWidget {
  final Locale locale;
  const LocaleScope({super.key, required this.locale, required super.child});

  static Locale of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<LocaleScope>();
    return scope?.locale ?? AppLocalizations.localeNotifier.value;
  }

  @override
  bool updateShouldNotify(LocaleScope oldWidget) => oldWidget.locale != locale;
}

/// Helper context extension for quick translations
extension LocalizationExtension on BuildContext {
  String tr(String key) {
    // Subscribe to locale changes so this widget rebuilds on language switch.
    LocaleScope.of(this);
    return AppLocalizations.translate(key);
  }
}
