name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl, zip
          tools: composer:v2

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Deploy via SSH and Rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete --exclude='.env' --exclude='/storage/' --exclude='/vendor/'"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/home/sapapimuntajat/sapconnect_app/"

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/sapapimuntajat/sapconnect_app/
            php artisan migrate --force
            php artisan optimize:clear
            php artisan filament:upgrade
